name: Deploy to AWS S3

on:
  push:
    branches:
      - main # or master, or whatever branch you want to trigger the sync

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # e.g., us-east-1, ap-southeast-1 (Dasmarinas is closer to ap-southeast-1)

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude '.git/*' --exclude '.github/*'
        # Explanation of `aws s3 sync` options:
        # `.` : Syncs the current directory (your entire repo after checkout).
        # `s3://${{ secrets.S3_BUCKET_NAME }}`: The destination S3 bucket.
        # `--delete`: Deletes files in the S3 bucket that are not in your GitHub repo.
        # `--exclude '.git/*'` and `--exclude '.github/*'`: Prevents syncing Git-related and workflow files.