name: Deploy React App to AWS S3

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a Linux runner for the build

    steps:
      - name: Checkout Repository # Get your source code
        uses: actions/checkout@v4

      - name: Set up Node.js # Install Node.js on the runner for npm/yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your desired Node.js version (e.g., '20', 'lts/*')

      - name: Install Dependencies # Install your project's npm dependencies
        run: npm install # or yarn install if you use yarn

      - name: Build React App # This is the crucial step!
        run: npm run build # or yarn build if you use yarn

      - name: Configure AWS Credentials # Set up AWS authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # Your S3 bucket's AWS region

      - name: Deploy build folder to S3 bucket # Sync the *build* folder
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude '.git/*' --exclude '.github/*'
        # Notice the './build' in 'aws s3 sync ./build ...'
        # This ensures only the contents of your generated 'build' folder are uploaded.