name: Deploy Build Files to AWS S3
on:
  push:
    branches:
      - main # or master, or whatever branch you want to trigger the sync
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred Node.js version
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Project
        run: npm run build
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1 # Singapore region (closest to Dasmariñas)
      
      - name: Deploy build files to S3 bucket
        run: |
          aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }} --delete
        # Explanation of `aws s3 sync` options:
        # `./build` : Syncs only the build directory contents to S3
        # `s3://${{ secrets.AWS_S3_BUCKET }}`: The destination S3 bucket
        # `--delete`: Deletes files in S3 that are not in your build directory
